### PR TITLE
Update BULK - CASE TRANSFER.vbs

### LINKED ISSUE #307: Enhancement to Case Transfer Script
I have added the option to the initial dialog box the option to transfer and caad note the details of a SINGLE case transfer.  I am not sure this is really a "bulk" script anymore?  I think it should be more of an "actions" script.  Thoughts?

### PR DESCRIPTION
**Pull request by khiestand**
I have added a drop down option in the first dialog box to transfer and caad note a single case.

Resolves #307

### CODE REVIEW

**Comment by RobertFewins-Kalb** [comment]
I'm not so sure about this one. We have your NOTES - CASE TRANSFER and then this BULK - CASE TRANSFER for sending out a lot of cases all at once. I'm thinking a nice enhancement might be to give users the option of putting the same case note on each case you are transferring out, but you are correct that this enhancement is not really a bulk script.

Something to discuss next Thursday?

**Comment by khiestand** [comment]
Oh  we do have my NOTES- CASE transfer one on the power pad?  I didn't realize as I am not at Wright CO today.  Yeah let's talk about it at the next call!

**Comment by RobertFewins-Kalb** [comment]
Sounds great! I'm going to leave this one hanging out there until then.

**Comment by RobertFewins-Kalb** [comment]
Conversation at phone call indicates there should be a single script for transferring cases.

**Pull request merged**
