### PR TITLE
Rename NOTES - MOD CAAD NOTE - CONTACT CHECKLIST.vbs to NOTES - MOD CA…

### PR DESCRIPTION
**Pull request by KallistaImdieke**
…AD NOTE - CONTACT CHECKLIST.vbs

Changed the Name of the Script to take out the :

### CODE REVIEW

**Comment by theVKC** [comment]
Thanks for this @KallistaImdieke! We also need to modify the name of the script in the "ALL SCRIPTS.vbs" file. Can you do that as well?

**Comment by KallistaImdieke** [comment]
Yes I will try and figure it out.  might not be until tomorrow morning

**Comment by theVKC** [comment]
@KallistaImdieke, I'm going to pull it in and I'll just update the menu. No worries!! Thanks for your help on it!

**Comment by KallistaImdieke** [comment]
Did you take care of this I done show a : in the name when I checked

**Comment by theVKC** [comment]
Mine looks resolved. Are you on the master branch?

**Pull request merged**
