### PR TITLE
Update NOTES - E-FILING.vbs

### PR DESCRIPTION
**Pull request by khiestand**
Added an edit box for E-Service Details.

### CODE REVIEW

**Comment by khiestand** [comment]
Wait don't pull this yet I need to change one thing still!

**Comment by khiestand** [comment]
@RobertFewins-Kalb How do I find my patch 9? lol

**Comment by RobertFewins-Kalb** [comment]
Right here-sies... https://github.com/khiestand/PRISM-Scripts/tree/patch-9

**Comment by RobertFewins-Kalb** [comment]
After you make the modifications, just create a new pull request...

image

**Comment by khiestand** [comment]
@RobertFewins-Kalb

**Comment by khiestand** [comment]
@RobertFewins-Kalb   Ok will do, It is still not exactly right sorry!  Technical difficulties over here!

**Pull request merged**
