### PR TITLE
Create Script FilesACTIONSACTIONS - EMPLOYMENT VERIFICATION.vbs

### PR DESCRIPTION
**Pull request by jlmartinone**
Please help finishing this. I have commented out what/where needs help.
If there is an error on the NCID/CPID script should stop to be correct before proceeding to CAAD
CAAD note for medical/dental needs an "if then" 
add CAWD if the medical/dental is marked yes

### CODE REVIEW

**Comment by RobertFewins-Kalb** [comment]
@jlmartinone I cannot accept this pull request. You need to rename the script to put the script into the script files folder, into the ACTIONS menu. You can go into your own repo into patch 2 (https://github.com/jlmartinone/PRISM-Scripts/tree/patch-2) and modify the file there. That will update the pull request. Email me if you have questions.

**Comment by RobertFewins-Kalb** [comment]
@jlmartinone here's an example of what the title should look like...

image

**Comment by jlmartinone** [comment]
@RobertFewins-Kalb 
I think I fixed it, please let me know if it still is not correct.
Thanks

**Comment by RobertFewins-Kalb** [comment]
Still not quite there.

When you go to create the file, start by being in the ACTIONS folder, then click to create file.
image


That will ensure you are putting the file into the correct folder.

**Comment by jlmartinone** [comment]
I will have Kelly help me after the call - thanks!

**Comment by RobertFewins-Kalb** [comment]
Kewl!

**Comment by RobertFewins-Kalb** [comment]
Closing

**Pull request closed without merging**
